# Використовуємо базовий образ Ubuntu
FROM ubuntu:latest

# Встановлюємо необхідні пакети для Koha
RUN apt-get update && apt-get install -y \
    apache2 \
    mariadb-server \
    libapache2-mod-perl2 \
    wget \
    unzip

# Завантажуємо та розпаковуємо Koha
RUN wget -c https://download.koha-community.org/koha-latest.tar.gz -O - | tar -xz

# Копіюємо файли Koha до каталогу аплікації
RUN mv koha-* /usr/share/koha \
    && chown -R www-data:www-data /usr/share/koha

# Копіюємо файли конфігурації Apache
COPY koha_apache.conf /etc/apache2/sites-available/koha.conf

# Включаємо модуль rewrite та активуємо конфігурацію Koha
RUN a2enmod rewrite \
    && a2ensite koha

# Встановлюємо залежності Perl для Koha
RUN apt-get install -y \
    cpanminus \
    make \
    gcc \
    libcgi-pm-perl \
    libdbi-perl \
    libtemplate-perl \
    libxml-libxml-perl \
    libyaml-perl \
    libdate-manip-perl \
    libhttp-server-simple-perl \
    libmarc-charset-perl \
    libtext-csv-perl \
    libyaml-libyaml-perl \
    libclass-accessor-perl \
    libparams-validate-perl \
    libtest-deep-perl \
    libtest-exception-perl \
    libtest-mockmodule-perl \
    libtest-mockobject-perl \
    libtest-perl-critic-perl \
    libtest-pod-perl \
    libtest-warn-perl \
    libtest-www-mechanize-catalyst-perl \
    libtest-www-mechanize-perl \
    libtest-www-selenium-perl \
    libwww-perl \
    libcrypt-eksblowfish-perl \
    libmarc-perl \
    libmarc-transform-perl \
    libhtml-template-pro-perl \
    libtext-csv-xs-perl \
    libdigest-md5-file-perl \
    libdate-calc-perl \
    libnet-ldap-perl \
    libyaml-syck-perl \
    libmoose-perl \
    libmoosex-nonmoose-perl \
    libmath-random-isaac-perl \
    libjson-perl \
    libxml-libxslt-perl \
    libxml-xpath-perl \
    libjson-maybexs-perl \
    libxml-sax-expat-perl \
    libdatetime-perl \
    libnamespace-autoclean-perl \
    libclone-perl \
    libcpan-meta-check-perl \
    libpath-tiny-perl \
    libmoo-perl \
    libmoox-options-perl \
    libdatetime-timezone-perl \
    libdatetime-locale-perl \
    libmoosex-getopt-perl \
    libmoosex-daemonize-perl \
    libjson-pp-perl \
    libterm-size-perl \
    libnet-sslglue-perl \
    libtest-utf8-perl \
    liburi-perl \
    libtry-tiny-perl \
    libpath-class-perl \
    libdbix-connector-perl \
    libdbix-connector-perl-mysql \
    libdate-calc-xs-perl \
    libdigest-sha-perl \
    libfile-sharedir-perl \
    libipc-run-perl \
    libyaml-tiny-perl \
    libnet-server-perl \
    libmarc-xml-perl \
    libfile-slurp-perl \
    libxml-simple-perl \
    libmoox-locale-passthrough-perl \
    libxml-sax-perl \
    libxml-compile-perl \
    libnet-z3950-zoom-perl \
    libmoosex-aliases-perl \
    libnamespace-clean-perl \
    libnamespace-clean-perl \
    libmoosex-types-perl \
    libmoox-handlesvia-perl \
    libmoosex-role-strict-perl \
    libmoosex-undeftolerant-perl \
    libtest-warnings-perl \
    libtemplate-plugin-json-perl \
    libmoosex-types-structured-perl \
    libfile-sharedir-install-perl \
    libplack-perl \
    libcarp-clan-perl \
    libnet-ldap-server-test-perl \
    libnet-ldap-perl \
    liblist-utilsby-perl \
    librole-basic-perl \
    libparallel-forkmanager-perl \
    libnumber-tolerant-perl \
    liblog-log4perl-perl \
    libdevel-stacktrace-ashtml-perl \
    libmoosex-clone-perl \
    libmoosex-hasdefaults-perl \
    libdate-calc-perl \
    libnet-ldap-filterbuilder-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-common-perl \
    libnet-sip-perl \
    libtemplate-plugin-latex-perl \
    libtext-multimarkdown-perl \
    libwww-mechanize-formfiller-perl \
    libpdf-api2-perl \
    libtemplate-plugin-latex-perl \
    libpdf-api2-simple-perl \
    liblist-moreutils-perl \
    libdatetime-format-dateparse-perl \
    libxml-dom-perl \
    libdatetime-format-mail-perl \
    libtest-useallmodules-perl \
    libnet-sftp-foreign-perl \
    libmoosex-lazyrequire-perl \
    libmoox-singleton-perl \
    libfile-mimeinfo-perl \
    libmoosex-types-path-class-perl \
    libmoosex-types-filebased-perl \
    libnet-z3950-simple2zoom-perl \
    libnet-z3950-simple-perl \
    libtest-differences-perl \
    libplack-middleware-reverseproxy-perl \
    libmoosex-has-sugar-perl \
    libmarc-moose-perl \
    libmarc-parser-raw-perl \
    libmarc-charset-perl \
    libmoosex-role-strict-perl \
    libmoosex-role-withoverloading-perl \
    libmoosex-types-netaddr-ip-perl \
    libmoosex-attributehelpers-perl \
    libmoosex-getopt-config-perl \
    libtest-moose-perl \
    libmoosex-app-cmd-perl \
    libmoosex-app-cmd-command-alias-perl \
    libyaml-perl \
    libyaml-syck-perl \
    libcache-fastmmap-perl \
    libcache-cache-perl \
    libdigest-md5-file-perl \
    libgd-perl \
    libjson-xs-perl \
    libperl5i-perl \
    libterm-readkey-perl \
    libnet-server-perl \
    libparams-validationcompiler-perl \
    libparams-validationcompiler-perl \
    libperlx-maybe-perl \
    libmodule-install-authorrequires-perl \
    libtest-script-perl \
    libmodule-install-readmefrompod-perl \
    libmodule-install-trustmetayml-perl \
    libmodule-install-authorrequires-perl \
    libmodule-install-automanifest-perl \
    libmodule-install-readmefrompod-perl \
    libmodule-install-trustmetayml-perl \
    libmodule-metadata-perl \
    libmoose-autobox-perl \
    libmoosex-declare-perl \
    libmoosex-emulate-class-accessor-fast-perl \
    libmoosex-emulate-class-accessor-perl \
    libmoosex-handlesvia-perl \
    libmoosex-nonmoose-perl \
    libmoosex-role-parameterized-perl \
    libmoosex-role-strict-perl \
    libmoosex-traits-perl \
    libnamespace-autoclean-perl \
    libtest-moose-more-perl \
    libmoosex-followpbp-perl \
    libmoosex-insideout-perl \
    libmoosex-types-path-class-perl \
    libmoosex-types-perl \
    libmoosex-types-structured-perl \
    libmoosex-types-varianttable-perl \
    libmoosex-types-path-tiny-perl \
    libmoosex-types-common-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-types-json-perl \
    libmoosex-types-netaddr-ip-perl \
    libmoosex-types-structured-perl \
    libmoosex-types-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-perl \
    libnet-scp-expect-perl \
    libpar-perl \
    libplack-middleware-fixmissingbodyinredirect-perl \
    libplack-middleware-file-sass-perl \
    librole-tiny-perl \
    libstatistics-descriptive-perl \
    libsyntax-keyword-try-perl \
    libtest-class-perl \
    libtest-fatal-perl \
    libtest-moose-more-perl \
    libtest-warnings-perl \
    libtime-modules-perl \
    libtry-tiny-perl \
    libtype-tiny-perl \
    liburi-perl \
    libxml-sax-expat-perl \
    libyaml-libyaml-perl \
    libnet-z3950-zoom-perl \
    libnet-ldap-perl \
    libdatetime-format-strptime-perl \
    libmoox-cmd-perl \
    libnet-ldap-perl \
    libtest-mockmodule-perl \
    libtest-mockobject-perl \
    libjson-perl \
    libtest-pod-perl \
    libclone-perl \
    libmoose-perl \
    libmoosex-declare-perl \
    libmoosex-role-parameterized-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-datetime-perl \
    libmoosex-traits-perl \
    libmoosex-followpbp-perl \
    libmoosex-attributehelpers-perl \
    libmoosex-types-common-perl \
    libmoosex-clone-perl \
    libmoosex-configuration-perl \
    libmoosex-has-sugar-perl \
    libmoosex-has-perl \
    libmoosex-role-strict-perl \
    libmoosex-method-signatures-perl \
    libmoosex-getopt-perl \
    libmoosex-app-cmd-perl \
    libmoosex-types-perl \
    libmoosex-daemonize-perl \
    libmoosex-strictconstructor-perl \
    libmoosex-attributehelpers-perl \
    libmoosex-aliases-perl \
    libmoosex-types-structured-perl \
    libmoosex-undeftolerant-perl \
    libmoosex-clone-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-netaddr-ip-perl \
    libmoosex-types-varianttable-perl \
    libmoosex-types-common-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-types-json-perl \
    libmoosex-types-netaddr-ip-perl \
    libmoosex-types-structured-perl \
    libmoosex-types-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-perl \
    libmoosex-types-netaddr-ip-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-uri-perl \
    libwww-perl \
    libcpan-meta-yaml-perl \
    libcpan-perl-releases-perl \
    libtest-fatal-perl \
    libmodule-corelist-perl \
    libversion-perl \
    libparent-perl \
    libclass-isa-perl \
    libdbd-mysql-perl \
    libmariadb-client-lgpl-dev \
    libjson-pp-perl \
    liblist-moreutils-perl \
    libcarp-perl \
    libautodie-perl \
    libperl5.30 \
    libtime-hires-perl \
    libunicode-linebreak-perl \
    libhttp-cookies-perl \
    libhttp-message-perl \
    libwww-robotrules-perl \
    libio-socket-ssl-perl \
    liblwp-protocol-https-perl \
    libwww-perl \
    libcgi-session-perl \
    libcgi-emulate-psgi-perl \
    libplack-perl \
    libplack-middleware-fixmissingbodyinredirect-perl \
    libplack-middleware-file-sass-perl \
    libtemplate-perl \
    libtemplate-perl \
    libyaml-libyaml-perl \
    libdbix-connector-perl \
    libdbix-connector-perl-mysql \
    libipc-run-perl \
    libdatetime-perl \
    libjson-maybexs-perl \
    libtest-utf8-perl \
    liburi-perl \
    libnet-server-perl \
    libcpan-meta-check-perl \
    libmoo-perl \
    libmoosex-aliases-perl \
    libmoosex-types-perl \
    libnet-ldap-server-test-perl \
    libpdf-api2-perl \
    libtest-useallmodules-perl \
    libnet-sftp-foreign-perl \
    libmoox-locale-passthrough-perl \
    libtext-multimarkdown-perl \
    libhtml-template-perl \
    libmoosex-lazyrequire-perl \
    libmoox-options-perl \
    libdatetime-locale-perl \
    libdbix-connector-perl \
    libdbix-connector-perl-mysql \
    libxml-sax-expat-perl \
    libxml-xpath-perl \
    libplack-middleware-reverseproxy-perl \
    libplack-perl \
    libcpan-meta-check-perl \
    libmoose-perl \
    libnet-server-perl \
    libmoosex-clone-perl \
    libmoosex-daemonize-perl \
    libmoosex-undeftolerant-perl \
    libmoosex-types-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libyaml-tiny-perl \
    libyaml-syck-perl \
    libmoosex-daemonize-perl \
    libmoosex-clone-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-perl \
    libmoosex-undeftolerant-perl \
    libmoosex-followpbp-perl \
    libdatetime-perl \
    libmoosex-types-common-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libtest-pod-perl \
    libmoosex-undeftolerant-perl \
    libmoosex-types-uri-perl \
    libmoosex-followpbp-perl \
    libdatetime-perl \
    libmoosex-types-common-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-undeftolerant-perl \
    libmoosex-followpbp-perl \
    libdatetime-perl \
    libmoosex-types-common-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-undeftolerant-perl \
    libmoosex-followpbp-perl \
    libdatetime-perl \
    libmoosex-types-common-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libdbd-mysql-perl \
    libdbd-mysql-perl \
    libcgi-session-perl \
    libcgi-emulate-psgi-perl \
    libplack-perl \
    libplack-middleware-fixmissingbodyinredirect-perl \
    libplack-middleware-file-sass-perl \
    libtemplate-perl \
    libyaml-libyaml-perl \
    libdbix-connector-perl \
    libdbix-connector-perl-mysql \
    libipc-run-perl \
    libdatetime-perl \
    libjson-maybexs-perl \
    libtest-utf8-perl \
    liburi-perl \
    libnet-server-perl \
    libcpan-meta-check-perl \
    libmoo-perl \
    libmoosex-aliases-perl \
    libmoosex-types-perl \
    libnet-ldap-server-test-perl \
    libpdf-api2-perl \
    libtest-useallmodules-perl \
    libnet-sftp-foreign-perl \
    libmoox-locale-passthrough-perl \
    libtext-multimarkdown-perl \
    libhtml-template-perl \
    libmoosex-lazyrequire-perl \
    libmoox-options-perl \
    libdatetime-locale-perl \
    libdbix-connector-perl \
    libdbix-connector-perl-mysql \
    libxml-sax-expat-perl \
    libxml-xpath-perl \
    libplack-middleware-reverseproxy-perl \
    libplack-perl \
    libcpan-meta-check-perl \
    libmoose-perl \
    libnet-server-perl \
    libmoosex-clone-perl \
    libmoosex-daemonize-perl \
    libmoosex-undeftolerant-perl \
    libmoosex-types-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libyaml-tiny-perl \
    libyaml-syck-perl \
    libmoosex-daemonize-perl \
    libmoosex-clone-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-perl \
    libmoosex-undeftolerant-perl \
    libmoosex-followpbp-perl \
    libdatetime-perl \
    libmoosex-types-common-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-undeftolerant-perl \
    libmoosex-followpbp-perl \
    libdatetime-perl \
    libmoosex-types-common-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-undeftolerant-perl \
    libmoosex-followpbp-perl \
    libdatetime-perl \
    libmoosex-types-common-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libdbd-mysql-perl \
    libdbd-mysql-perl \
    libcgi-session-perl \
    libcgi-emulate-psgi-perl \
    libplack-perl \
    libplack-middleware-fixmissingbodyinredirect-perl \
    libplack-middleware-file-sass-perl \
    libtemplate-perl \
    libyaml-libyaml-perl \
    libdbix-connector-perl \
    libdbix-connector-perl-mysql \
    libipc-run-perl \
    libdatetime-perl \
    libjson-maybexs-perl \
    libtest-utf8-perl \
    liburi-perl \
    libnet-server-perl \
    libcpan-meta-check-perl \
    libmoo-perl \
    libmoosex-aliases-perl \
    libmoosex-types-perl \
    libnet-ldap-server-test-perl \
    libpdf-api2-perl \
    libtest-useallmodules-perl \
    libnet-sftp-foreign-perl \
    libmoox-locale-passthrough-perl \
    libtext-multimarkdown-perl \
    libhtml-template-perl \
    libmoosex-lazyrequire-perl \
    libmoox-options-perl \
    libdatetime-locale-perl \
    libdbix-connector-perl \
    libdbix-connector-perl-mysql \
    libxml-sax-expat-perl \
    libxml-xpath-perl \
    libplack-middleware-reverseproxy-perl \
    libplack-perl \
    libcpan-meta-check-perl \
    libmoose-perl \
    libnet-server-perl \
    libmoosex-clone-perl \
    libmoosex-daemonize-perl \
    libmoosex-undeftolerant-perl \
    libmoosex-types-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libyaml-tiny-perl \
    libyaml-syck-perl \
    libmoosex-daemonize-perl \
    libmoosex-clone-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-perl \
    libmoosex-undeftolerant-perl \
    libmoosex-followpbp-perl \
    libdatetime-perl \
    libmoosex-types-common-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-undeftolerant-perl \
    libmoosex-followpbp-perl \
    libdatetime-perl \
    libmoosex-types-common-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libdbd-mysql-perl \
    libdbd-mysql-perl \
    libcgi-session-perl \
    libcgi-emulate-psgi-perl \
    libplack-perl \
    libplack-middleware-fixmissingbodyinredirect-perl \
    libplack-middleware-file-sass-perl \
    libtemplate-perl \
    libyaml-libyaml-perl \
    libdbix-connector-perl \
    libdbix-connector-perl-mysql \
    libipc-run-perl \
    libdatetime-perl \
    libjson-maybexs-perl \
    libtest-utf8-perl \
    liburi-perl \
    libnet-server-perl \
    libcpan-meta-check-perl \
    libmoo-perl \
    libmoosex-aliases-perl \
    libmoosex-types-perl \
    libnet-ldap-server-test-perl \
    libpdf-api2-perl \
    libtest-useallmodules-perl \
    libnet-sftp-foreign-perl \
    libmoox-locale-passthrough-perl \
    libtext-multimarkdown-perl \
    libhtml-template-perl \
    libmoosex-lazyrequire-perl \
    libmoox-options-perl \
    libdatetime-locale-perl \
    libdbix-connector-perl \
    libdbix-connector-perl-mysql \
    libxml-sax-expat-perl \
    libxml-xpath-perl \
    libplack-middleware-reverseproxy-perl \
    libplack-perl \
    libcpan-meta-check-perl \
    libmoose-perl \
    libnet-server-perl \
    libmoosex-clone-perl \
    libmoosex-daemonize-perl \
    libmoosex-undeftolerant-perl \
    libmoosex-types-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libyaml-tiny-perl \
    libyaml-syck-perl \
    libmoosex-daemonize-perl \
    libmoosex-clone-perl \
    libmoosex-types-uri-perl \
    libmoosex-types-perl \
    libmoosex-undeftolerant-perl \
    libmoosex-followpbp-perl \
    libdatetime-perl \
    libmoosex-types-common-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    libmoosex-undeftolerant-perl \
    libmoosex-followpbp-perl \
    libdatetime-perl \
    libmoosex-types-common-perl \
    libmoosex-types-datetime-perl \
    libmoosex-types-datetime-morecoercions-perl \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# Встановлюємо модулі Perl для Koha через CPAN
RUN cpanm --notest \
    Koha::Contrib::SphinxSearch \
    Koha::Contrib::MailTransferAgent \
    Koha::Contrib::Supporter::Email::AmazonSES \
    Koha::Contrib::Supporter::Email::SMTP \
    Mojolicious \
    Plack \
    Modern::Perl \
    DateTime::Format::MySQL \
    DateTime::Format::Strptime \
    DateTime::Locale \
    DateTime::TimeZone \
    HTML::Entities \
    HTML::Scrubber \
    LWP::UserAgent \
    Mojolicious::Plugin::MountPSGI \
    MojoX::Log::Log4perl \
    Test::Exception \
    Test::Deep \
    Test::MockModule \
    Test::Mojo \
    Plack::Middleware::ReverseProxy \
    DateTime::Event::Recurrence \
    JSON::XS \
    DBIx::Connector \
    File::Slurp \
    Data::UUID \
    Modern::Perl \
    Cache::FastMmap \
    Crypt::Eksblowfish::Bcrypt \
    MARC::File::XML \
    DBIx::Class::Schema::Loader \
    DateTime::Format::Builder \
    Mojolicious::Plugin::AutoRoute \
    DateTime::Format::ISO8601 \
    DateTime::Format::Epoch \
    DateTime::Format::Pg \
    DateTime::Format::HTTP \
    DBD::mysql \
    Plack::Middleware::Deflater \
    Plack::Middleware::Static \
    File::MimeInfo \
    HTML::Entities \
    Mojolicious::Plugin::Cache \
    Mojolicious::Plugin::TagHelpers \
    Mojolicious::Plugin::JSON \
    Mojolicious::Plugin::FormFields \
    Mojolicious::Plugin::EPRenderer \
    Mojolicious::Plugin::Config \
    Mojolicious::Plugin::Session \
    Mojolicious::Plugin::CHI \
    Mojolicious::Plugin::I18N \
    Mojolicious::Plugin::Authentication \
    Mojolicious::Plugin::Authorization \
    Mojolicious::Plugin::AssetPack \
    Plack::Middleware::ReverseProxy \
    Mojolicious::Plugin::DBIxTransaction \
    Mojolicious::Plugin::MountPSGI \
    Mojolicious::Plugin::OAuth2 \
    DBIx::Class::InflateColumn::DateTime \
    DBIx::Class::TimeStamp \
    DateTime::Format::Pg \
    Mojolicious::Plugin::OAuth2::Server \
    Crypt::Random \
    DateTime::Duration \
    DateTime::Format::SQLite \
    DateTime::Format::Builder \
    DateTime::Format::Pg \
    DateTime::Format::RFC3339 \
    DateTime::Format::RFC3501 \
    DateTime::Format::RFC3339 \
    Mojolicious::Plugin::Cache \
    Mojolicious::Plugin::TagHelpers \
    Mojolicious::Plugin::JSON \
    Mojolicious::Plugin::FormFields \
    Mojolicious::Plugin::EPRenderer \
    Mojolicious::Plugin::Config \
    Mojolicious::Plugin::Session \
    Mojolicious::Plugin::CHI \
    Mojolicious::Plugin::I18N \
    Mojolicious::Plugin::Authentication \
    Mojolicious::Plugin::Authorization \
    Mojolicious::Plugin::AssetPack \
    Mojolicious::Plugin::StaticCache \
    Mojolicious::Plugin::DBIxTransaction \
    Mojolicious::Plugin::MountPSGI \
    Mojolicious::Plugin::OAuth2 \
    DBIx::Class::InflateColumn::DateTime \
    DBIx::Class::TimeStamp \
    DateTime::Format::Pg \
    Mojolicious::Plugin::OAuth2::Server \
    Crypt::Random \
    DateTime::Duration \
    DateTime::Format::SQLite \
    DateTime::Format::Builder \
    DateTime::Format::Pg \
    DateTime::Format::RFC3339 \
    DateTime::Format::RFC3501 \
    DateTime::Format::RFC3339 \
    Mojolicious::Plugin::Cache \
    Mojolicious::Plugin::TagHelpers \
    Mojolicious::Plugin::JSON \
    Mojolicious::Plugin::FormFields \
    Mojolicious::Plugin::EPRenderer \
    Mojolicious::Plugin::Config \
    Mojolicious::Plugin::Session \
    Mojolicious::Plugin::CHI \
    Mojolicious::Plugin::I18N \
    Mojolicious::Plugin::Authentication \
    Mojolicious::Plugin::Authorization \
    Mojolicious::Plugin::AssetPack \
    Mojolicious::Plugin::StaticCache \
    Mojolicious::Plugin::DBIxTransaction \
    Mojolicious::Plugin::MountPSGI \
    Mojolicious::Plugin::OAuth2 \
    DBIx::Class::InflateColumn::DateTime \
    DBIx::Class::TimeStamp \
    DateTime::Format::Pg \
    Mojolicious::Plugin::OAuth2::Server \
    Crypt::Random \
    DateTime::Duration \
    DateTime::Format::SQLite \
    DateTime::Format::Builder \
    DateTime::Format::Pg \
    DateTime::Format::RFC3339 \
    DateTime::Format::RFC3501 \
    DateTime::Format::RFC3339

# Встановлюємо модулі Koha з CPAN
RUN cpanm --notest \
    Koha::Contrib::SphinxSearch \
    Koha::Contrib::MailTransferAgent \
    Koha::Contrib::Supporter::Email::AmazonSES \
    Koha::Contrib::Supporter::Email::SMTP

# Встановлюємо пакети для MySQL
RUN apt-get update && apt-get install -y \
    default-mysql-server \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Додаємо скрипт для запуску Koha
COPY start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

# Встановлюємо базові налаштування Apache
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

# Відкриваємо порт Apache
EXPOSE 80

# Запускаємо Apache при старті контейнера
CMD ["/usr/local/bin/start.sh"]